name: Deploy to Porter

on:
  push:
    branches:
    - master

jobs:
  porter-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Deploy stack and send logs to web service
      run: |
        python - <<END
        import requests
        import subprocess

        # Use the Porter CLI command for deployment as 'cmd'
        cmd = "porter apply -f porter.yaml"

        env = {
          "PORTER_CLUSTER": "1",
          "PORTER_HOST": "https://9562-2600-4040-2300-d400-c75-d52a-cfa7-e633.ngrok-free.app",
          "PORTER_PROJECT": "1",
          "PORTER_STACK_NAME": "asdfads",
          "PORTER_TAG": "${{ env.sha_short }}",
          "PORTER_TOKEN": "${{ secrets.PORTER_STACK_1_1 }}",
        }

        proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env={**os.environ, **env})

        while True:
          output = proc.stdout.readline()
          if output == '' and proc.poll() is not None:
            break
          if output:
            print(output.strip())
            # send the log to your web service
            log_data = {'log': output.strip()}
            requests.post('https://e81e-160-72-72-58.ngrok-free.app', data=log_data)
        rc = proc.poll()
        END
